#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Linting All Files to assure consistency to OpenForge standards..."
npx nx run-many --all --target=lint --fix

echo "Verifying Project Builds..."
npx nx build
