#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Setting Node Memory to 8 GB"
export NODE_OPTIONS="--max-old-space-size=8192"

echo "Verifying Project Builds..."
npx nx build
npx lint-staged
echo "Linting Staged Files for consistency to OpenForge standards..."